version: "3"
services:
  quart-app-1:
    container_name: "quart-app-1"
    environment:
    - POOLNAME=pool201
    - VERSION=2
    - AGENTID=Agent1
    - AGENTKEY=SuperAgent1!
    - SEED=000000000000000000000000Steward1
    restart: always
    image: quart-app
    build:
      context: .
      dockerfile: quart_app/Dockerfile
    ports:
    - "9001:9000"
    volumes:
    - ./quart_app:/home/quart
  quart-app-2:
    container_name: "quart-app-2"
    environment:
    - POOLNAME=pool202
    - VERSION=2
    - AGENTID=Agent2
    - AGENTKEY=SuperAgent2!
    - SEED=000000000000000000000000Steward1
    restart: always
    image: quart-app
    build:
      context: .
      dockerfile: quart_app/Dockerfile
    ports:
    - "9002:9000"
    volumes:
    - ./quart_app:/home/quart
  quart-app-3:
    container_name: "quart-app-3"
    environment:
    - POOLNAME=pool203
    - VERSION=2
    - AGENTID=Agent3
    - AGENTKEY=SuperAgent3!
    - SEED=000000000000000000000000Steward1
    restart: always
    image: quart-app
    build:
      context: .
      dockerfile: quart_app/Dockerfile
    ports:
    - "9003:9000"
    volumes:
    - ./quart_app:/home/quart

#  quart-nginx-1:
#    image: quart-nginx
#    build:
#      context: .
#      dockerfile: nginx/Dockerfile
#    ports:
#    - "8080:80"
#    links:
#    - quart-app-1
#    depends_on:
#    - quart-app-1
#  quart-nginx-2:
#    image: quart-nginx
#    build:
#      context: .
#      dockerfile: nginx/Dockerfile
#    ports:
#    - "9080:80"
#    links:
#    - quart-app-2
#    depends_on:
#    - quart-app-2
